export const CATEGORY_REQUEST = "CATEGORY_REQUEST"
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS"
export const CATEGORY_FAILURE = "CATEGORY_FAILURE"

export const CATEGORY_REQUEST_POST = "CATEGORY_REQUEST_POST"
export const CATEGORY_SUCCESS_POST = "CATEGORY_SUCCESS_POST"
export const CATEGORY_FAILURE_POST = "CATEGORY_FAILURE_POST"

export const CATEGORY_REQUEST_UPDATE = "CATEGORY_REQUEST_UPDATE"
export const CATEGORY_SUCCESS_UPDATE = "CATEGORY_SUCCESS_UPDATE"
export const CATEGORY_FAILURE_UPDATE = "CATEGORY_FAILURE_UPDATE"


export const CATEGORY_REQUEST_DELETE = "CATEGORY_REQUEST_DELETE"
export const CATEGORY_SUCCESS_DELETE = "CATEGORY_SUCCESS_DELETE"
export const CATEGORY_FAILURE_DELETE = "CATEGORY_FAILURE_DELETE"