export const PRODUCT_REQUEST = "PRODUCT_REQUEST"
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS"
export const PRODUCT_FAILURE = "PRODUCT_FAILURE"


export const PRODUCT_REQUEST_POST = "PRODUCT_REQUEST_POST"
export const PRODUCT_SUCCESS_POST = "PRODUCT_SUCCESS_POST"
export const PRODUCT_FAILURE_POST = "PRODUCT_FAILURE_POST"

export const PRODUCT_REQUEST_UPDATE = "PRODUCT_REQUEST_UPDATE"
export const PRODUCT_SUCCESS_UPDATE = "PRODUCT_SUCCESS_UPDATE"
export const PRODUCT_FAILURE_UPDATE = "PRODUCT_FAILURE_UPDATE"


export const PRODUCT_REQUEST_DELETE = "PRODUCT_REQUEST_DELETE"
export const PRODUCT_SUCCESS_DELETE = "PRODUCT_SUCCESS_DELETE"
export const PRODUCT_FAILURE_DELETE = "PRODUCT_FAILURE_DELETE"